### ISSUE TITLE
Git auth problem when binding /var/lib/git to a localfolder on host

### ISSUE THREAD

**Issue by zjoasan** [bacnh85/docker-gitolite-cgit#1]
I've been experimenting a lot with your image since i needed a temporary gitolite based git for building some shim to ssh import/mirror a repo from external source into a gitea(which still after 3 year since first issue reported still doesn't support).

So I looked for a gitolite docker, and haveing a http interface is helpful but no really needed, but still I had a good feeling abuout your image. I started it like you suggested in readme the first time, no problem geting ssh -p 5622 git@myserver info.

Nice i thought, now lets setup the git storage so I can access it from host-system, so I  -v /gitstorage/gitolite:/var/lib/git  

Somehow that makes the initial .pub invalid?? is it file rights of the auth.keys file?? I can't make heads or tails of the issue.

System is a Ubuntu Server 20.04, running:
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
![web_shell_screen shot](https://user-images.githubusercontent.com/18213901/185646911-3bf0cfe5-6b2c-49a2-ab60-ec7d6a03b94c.png)
![cgit_port_screenshot](https://user-images.githubusercontent.com/18213901/185646916-36d1f1d2-190c-42a0-af65-5d08ee3fbc81.png)

**Comment by bacnh85** [comment]
@zjoasan apology for late reply as I do not have email notification about this issue.

Your issue is related to `bind mount` vs `volume mount`. If you are using bind mount, data will not be initialized once docker container is created.

You can first copy the content of `/var/lib/git` from running container with `docker cp` and run the new container again.
